const institutes_name=[
    'Acropolis Institute of Technology & Research:Indore (2005)',
    'Adina Institute of Science & Technology: Sagar(2009)',
    'Aditya College of Technology & Science: Satna(2007)',
    'All Saints College of Technology: Bhopal (2002)',
    'Alpine Institute of Technology: Ujjain (2007)',
    'Annie Institute of Technology and ResearchCentre: Chhindwara (2013)',
    'Astral Institute of Technology & Research: Indore(2006)',
    'BADERIA GLOBAL INSTITUTE OF ENGINEERING &MANAGEMENT: JABALPUR',
    'BM College of Technology: Indore (2007)',
    'Babulal Tarabai Institute of Research &Technology: Sagar (2008)',
    'Bansal College of Engineering: Obedullaganj:Raisen (2002)',
    'Bansal Institute of Research & Technology:Bhopal (2007)',
    'Bansal Institute of Research Technology &Science: Bhopal (2008)',
    'Bansal Institute of Science & Technology: Bhopal(2000)',
    'Bethesda Institute of Technology and Science:Gwalior (2011)',
    'Bhopal Institute of Technology & Management:Bhopal (2009)',
    'Bhopal Institute of Technology & Science: Bhopal(2002)',
    'Bhopal Institute of Technology: Bhopal (2007)',
    'Chameli Devi Group of Institutions: Indore(2006)',
    'Corporate Institute of Science & Technology:Bhopal (2008)',
    'Global Institute of Engineering & Science:Barwani (2008)',
    'Guru Ramdas Khalsa Institute of Science &Technology: Jabalpur (1997)',
    'Gwalior Institute of Information Technology:Gwalior (2008)',
    'Gyan Ganga College of Technology: Jabalpur(2006)',
    'Gyan Ganga Institute of Technology & Science:Jabalpur (2003)',
    'Gyan Sagar College of Engineering: Sagar (2009)',
    'Hitkarni College of Engineering & Technology:Jabalpur (1997)',
    'IES College of Technology: Bhopal (2007)',
    'IPS Academy: Institute of Engineering andScience: Indore (1999)',
    'IPS College of Technology & Management:Gwalior (2007)',
    'Indira Gandhi Engineering College: Sagar (IGEC)(1981)',
    'Indore Institute of Science & Technology: Indore(2003)',
    'Infinity Management & Engineering College:Sagar (2008)',
    'Institute of Engineering Jiwaji University:Gwalior (1996)',
    'Institute of Engineering and Technology: DAVV:Indore (1996)',
    'Institute of Peoples Science and Technology:Chitrakoot: Satna (1991)',
    'Institute of Technology and Management:Gwalior (1997)',
    'JAWAHARLAL INSTITUTE OF TECHNOLOGY:BORAWAN(M.C.A.)',
    'Jabalpur Engineering College: Jabalpur: (JEC)(1947)',
    'Jabalpur Engineering College: Jabalpur: (JEC) (1947)',
    'Jai Narain College of Technology: Bhopal (2003)',
    'Jawaharlal Institute of Technology: Borawan:Khargone (1997)',
    'Jawaharlal Nehru College of Technology: Rewa(2007)',
    'Kailash Narayan Patidar College of Science &Technology: Bhopal (2008)',
    'Kopal Institute of Science & Technology: Bhopal(2009)',
    'LNCT (BHOPAL) INDORE CAMPUS (2006)',
    'Lakshmi Narain College of TechnologyExcellence: Bhopal (2007)',
    'Lakshmi Narain College of Technology & Science(RIT): Indore (2002)',
    'Lakshmi Narain College of Technology & Science:Bhopal (2006)',
    'Lakshmi Narain College of Technology: Bhopal(1994)',
    'Lakshmi Narain College of Technology: Indore(2004)',
    'Lakshmi Narain College of Technology: Jabalpur(2008)',
    'Laxmipati Institute of Science & Technology:Bhopal (2008)',
    'Madhav Institute of Technology and Science:Gwalior (1957)',
    'Madhav Institute of Technology and Science: Gwalior (1957)',
    'Mahakal Institute Technology & Management:Ujjain (2007)',
    'Mahakal Instute of Technology: Ujjain (2001)',
    'Maharana Pratap College of Technology: Gwalior(1996)',
    'Malwa Institute of Science & Technology: Indore(2008)',
    'Malwa Institute of Technology: Indore (2004)',
    'Mathura Devi Institute of Technology &Management: Indore (2007)',
    'Millenium Institute of Technology and Science:Bhopal (2007)',
    'Millenium Institute of Technology: Bhopal (2009)',
    'Mittal Institute of Technology: Bhopal (2007)',
    'NRI Institute of Information Science &Technology: Bhopal (2001)',
    'NRI Institute of Research & Technology: Bhopal(2008)',
    'Nagaji Institute of Technology & Management:Gwalior (2003)',
    'Nowgong Engineering College: Nowgong (NEC)(2012)',
    'Oriental College of Technology: Bhopal (2002)',
    'Oriental Institute of Science & Technology:Bhopal (1995)',
    'Oriental Institute of Science & Technology:Jabalpur (2008)',
    'PT. DEVPRABHAKAR SHASTRI COLLEGE OFTECHNOLOGY: Chhatarpur (2010)',
    'Patel College of Science & Technology: Bhopal(2002)',
    'Patel College of Science & Technology: Indore(2005)',
    'Prashantee Institute of Technology & Science:Ujjain (2008)',
    'Prestige Institute of Engineering Managementand Research: Indore (2008)',
    'Radha Raman Institute of Technology: & Science:Bhopal (2003)',
    'Radharaman Engineering College: Bhopal (2006)',
    'Rajeev Gandhi Prodyogiki Mahavidhyalaya:Bhopal (2006)',
    'Rewa Engineering College: Rewa (REC) (1964)',
    'Rewa Institute of Technology: Rewa (2003)',
    'Rustamji Institute of Technology: Tekanpur:Gwalior (1999)',
    'SATPUDA COLLEGE OF ENGINEERING ANDPOLYTECHNIC',
    'SCHOOL OF INFORMATION TECHNOLOGY: RGPVBHOPAL',
    'SGBM Institute of Technology & Science:Jabalpur (2008)',
    'Sagar Institute of Research & Technology -Excellence: Bhopal (2008)',
    'Sagar Institute of Research & Technology:Bhopal (2003)',
    'Sagar Institute of Science & Technology (SISTEC)Bhopal (2007)',
    'Sagar Institute of Science Technology &' +
      'Research: (SISTec-R): Bhopal (2009)',
    'Sagar Institute of Science: Technology &' +
      'Engineering(SISTec-E): Bhopal (2009)',
    'Samrat Ashok Technological Institute: Vidisha(1960)',
    'Saraswati Institute of Engineering & Technology:Jabalpur (2008)',
    'School of Engineering and Technology: VikramUniversity: Ujjain (2011)',
    'Scope College of Engineering Bhopal (2005)',
    'Sha-Shib College of Technology: Bhopal (2009)',
    'Shiv Kumar Singh Institute of Technology &Science: Indore (2007)',
    'Shivajirao Kadam Institute of Technology and' +
      'Management-Technical Campus: Indore (2009)',
    'Shreejee Institute of Technology andManagement: Khargone (2010)',
    'Shri Balaji Institute of Technology &Management: Betul (2009)',
    'Shri Dadaji Institute of Technology & Science:Khandwa',
    'Shri G.S. Institute of Technology & Science:Indore (M.P.) (1952)',
    'Shri G.S. Institute of Technology & Science: Indore (M.P.) (1952)',
    'Shri Guru Sandipani Institute of Technology &Science: Ujjain (2009)',
    'Shri Ram College of Engineering & Management:Banmore (1998)',
    'Shri Ram Group of Institution (Faculty of' +
      'Engineering: Pharmacy: MBA: MCA): Jabalpur (2009)',
    'Shri Ram Group of Institution (Faculty of Engineering: Pharmacy: MBA: MCA): Jabalpur' +
      '(2009)',
    'Shri Ram Institute of Information Technology:Banmore: Morena (2007)',
    'Shri Ram Institute of Science & Technology:Jabalpur (2007)',
    'Shri Ram Institute of Technology: Jabalpur(2001)',
    'Shri Rawatpura Sarkar Institute of Technology &Science: Datia (2002)',
    'Shri Yogendra Sagar Institute of Technology &Science: Ratlam (2008)',
    'Srajan Institute of Tech.: Management &Science: Ratlam (2009)',
    'Sri Aurobindo Institute of Technology: Indore(2009)',
    'St. Aloysius Institute of Technology: Jabalpur(2009)',
    'Sushila Devi Bansal College of Engineering:Indore (2006)',
    'Sushila Devi Bansal College of Technology:indore (2005)',
    'Swami Vivekanand College of Engineering:Indore (2004)',
    'TECHNOCRATS INSTITUTE OF TECHNOLOGY-' +
      'COMPUTER SCIENCE AND ENGINEERING: BHOPAL',
    'TECHNOCRATS INSTITUTE OF TECHNOLOGY- COMPUTER SCIENCE AND ENGINEERING:' +
      'BHOPAL',
    'Takshshila Institute of Engineering &Technology: Jabalpur (2004)',
    'Technocrats Institute of Technology & Science:Bhopal (2007)',
    'Technocrats Institute of Technology (Excellence):Bhopal (2007)',
    'Technocrats Institute of Technology: Bhopal(2000)',
    'Thakur Shiv Kumar Singh Memorial EngineeringCollege: Burhanpur (2011)',
    'Trinity Institute of Technology & Research:Bhopal (2008)',
    'Truba Institute of Engineering & InformationTechnology: Bhopal (2001)',
    'UJJAIN ENGINEERING COLLEGE (FORMERLYGOVT. ENGG. COLLEGE ESTB. IN 1966)',
    'UNIVERSITY INSTITUTE OF TECHNOLOGY RGPV:SHIVPURI (2020)',
    'University Institute of Technology BarkatullahUniversity: Bhopal (1997)',
    'University Institute of Technology RGPV: Bhopal(1986)',
    'University Institute of Technology: Jhabua' +
      '(Constituent College of RGPV)* (2015)',
    'University Institute of Technology: Shahdol' +
      '(Constituent College of RGPV)* (2015)',
    'VNS GROUP OF INSTITUTIONS: BHOPAL (2006)',
    'Vaishnavi Institutes of Technology and Science:Raisen (2010)',
    'Vidhyapeeth Institute of Science & Technology:Bhopal (2009)',
    'Vikrant Institute of Technology & ManagementIndore (2007)',
    'Vikrant Institute of Technology & Management:Gwalior (2009)',
    'Vindhya Institute of Technology & Science: Satna(2002)'
  ]

  export default  institutes_name;